n1 = float(input("Enter first number: "))
n2 = float(input("Enter second number: "))
print(f"{n1} + {n2} = {n1+n2}")
print("{} - {} = {}".format(n1, n2, n1-n2))
print(str(n1) + " x " + str(n2) + " = " + str(n1*n2))
print(n1,"/",n2,"=", n1/n2)
print(f"{n1}^{n2} = {n1**n2}")
